export const SPOT_TYPE = [
  // { id: 'accounting', title: '会計' },
  // { id: 'airport', title: '空港' },
  { id: 'amusement_park', title: '遊園地' },
  { id: 'aquarium', title: '水族館' },
  { id: 'art_gallery', title: 'アートギャラリー' },
  // { id: 'atm', title: 'ATM' },
  { id: 'bakery', title: 'ベーカリー' },
  // { id: 'bank', title: 'バンク' },
  { id: 'bar', title: 'バー' },
  // { id: 'beauty_salon', title: 'ビューティーサロン' },
  // { id: 'bicycle_store', title: '自転車屋' },
  { id: 'book_store', title: '書店' },
  { id: 'bowling_alley', title: 'ボーリング場' },
  // { id: 'bus_station', title: 'バス停' },
  { id: 'cafe', title: 'カフェ' },
  { id: 'campground', title: 'キャンプ場' },
  // { id: 'car_dealer', title: 'カーディーラー' },
  // { id: 'car_rental', title: 'レンタカー' },
  // { id: 'car_repair', title: '自動車修理' },
  // { id: 'car_wash', title: '洗車' },
  // { id: 'casino', title: 'カジノ' },
  // { id: 'cemetery', title: 'お墓' },
  // { id: 'church', title: '教会' },
  // { id: 'city_hall', title: '市役所' },
  { id: 'clothing_store', title: '衣料品店' },
  // { id: 'convenience_store', title: 'コンビニ' },
  // { id: 'courthouse', title: '裁判所' },
  // { id: 'dentist', title: '歯科医' },
  { id: 'department_store', title: 'デパート' },
  // { id: 'doctor', title: '医師' },
  // { id: 'drugstore', title: '薬局' },
  // { id: 'electrician', title: '電気技師' },
  // { id: 'electronics_store', title: '電気店' },
  // { id: 'embassy', title: '大使館' },
  // { id: 'fire_station', title: '消防署' },
  // { id: 'florist', title: '花屋' },
  // { id: 'funeral_home', title: '葬儀場' },
  { id: 'furniture_store', title: '家具屋' },
  // { id: 'gas_station', title: 'ガソリンスタンド' },
  // { id: 'gym', title: 'ジム' },
  // { id: 'hair_care', title: 'ヘアケア' },
  // { id: 'hardware_store', title: '金物屋' },
  // { id: 'hindu_temple', title: 'ヒンドゥー寺院' },
  { id: 'home_goods_store', title: '家庭用品店' },
  // { id: 'hospital', title: '病院' },
  // { id: 'insurance_agency', title: '保険代理店' },
  { id: 'jewelry_store', title: '宝石店' },
  // { id: 'laundry', title: 'ランドリー' },
  // { id: 'lawyer', title: '弁護士' },
  { id: 'library', title: '図書館' },
  // { id: 'light_rail_station', title: 'ライトレール駅' },
  // { id: 'liquor_store', title: '酒屋' },
  // { id: 'local_government_office', title: '自治体' },
  // { id: 'locksmith', title: '錠前屋' },
  { id: 'lodging', title: '宿泊' },
  // { id: 'meal_delivery', title: '食事配達' },
  // { id: 'meal_takeaway', title: '食事持ち帰り' },
  // { id: 'mosque', title: 'モスク' },
  // { id: 'movie_rental', title: '映画レンタル' },
  { id: 'movie_theater', title: '映画館' },
  // { id: 'moving_company', title: '引っ越し会社' },
  { id: 'museum', title: '博物館' },
  { id: 'night_club', title: 'ナイトクラブ' },
  // { id: 'painter', title: '画家' },
  { id: 'park', title: 'パーク' },
  // { id: 'parking', title: 'パーキング' },
  { id: 'pet_store', title: 'ペットショップ' },
  // { id: 'pharmacy', title: '薬局' },
  // { id: 'physiotherapist', title: '理学療法士' },
  // { id: 'plumber', title: '配管工' },
  // { id: 'police', title: '警察' },
  // { id: 'post_office', title: '郵便局' },
  // { id: 'primary_school', title: '小学校' },
  // { id: 'real_estate_agency', title: '不動産会社' },
  { id: 'restaurant', title: '飲食店' },
  // { id: 'roofing_contractor', title: '屋根ふき業者' },
  // { id: 'rv_park', title: 'RV Park' },
  // { id: 'school', title: '学校' },
  // { id: 'secondary_school', title: '中等学校' },
  { id: 'shoe_store', title: '靴屋' },
  { id: 'shopping_mall', title: 'ショッピングモール' },
  { id: 'spa', title: 'スパ' },
  // { id: 'stadium', title: 'スタジアム' },
  // { id: 'storage', title: 'ストレージ' },
  // { id: 'store', title: 'お店' },
  // { id: 'subway_station', title: '地下鉄の駅' },
  { id: 'supermarket', title: 'スーパーマーケット' },
  // { id: 'synagogue', title: 'シナゴーグ' },
  // { id: 'taxi_stand', title: 'タクシー乗り場' },
  { id: 'tourist_attraction', title: '観光の名所' },
  // { id: 'train_station', title: '鉄道駅' },
  // { id: 'transit_station', title: 'トランジット駅' },
  // { id: 'travel_agency', title: '旅行会社' },
  // { id: 'university', title: '大学' },
  // { id: 'veterinary_care', title: '獣医療' },
  { id: 'zoo', title: '動物園' },
];
